# -*- coding: utf-8 -*-
"""Projeto IA III.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7QBJPYQqS0tpC9JDwpFFX6FKE55pVim

# **Data Understanding**
"""



"""# **Data Preparation**"""



"""# **Modelling**"""



"""# **Evaluation**"""



"""# **Deployment**"""

